"use strict";

const DEFAULT_MCP_PROTOCOL_VERSION = "2025-06-18";
const DEFAULT_MCP_REQUEST_TIMEOUT_MS = 15000;

module.exports = {
  DEFAULT_MCP_PROTOCOL_VERSION,
  DEFAULT_MCP_REQUEST_TIMEOUT_MS,
};
