"use strict";

const METADATA_TOOLS = [
  "yeelight_metadata.list_groups",
  "yeelight_metadata.list_houses",
  "yeelight_metadata.list_tasks",
  "yeelight_metadata.list_actions",
  "yeelight_metadata.get_action_schema",
  "yeelight_metadata.execute_task",
];

const METADATA_SAFETY = ["validate", "dryRun", "sideEffect", "candidateGate"];

const METADATA_GROUPS = [
  {
    id: "family_space",
    title: "家庭与空间",
    summary: "管理家庭、房间、区域和家庭成员。",
  },
  {
    id: "device_onboarding",
    title: "设备接入与配网",
    summary: "完成设备槽位创建、配网、网关接入和 Matter 配对。",
  },
  {
    id: "device_management",
    title: "设备管理",
    summary: "查询、修改、移动、解绑和删除设备，以及维护设备组。",
  },
  {
    id: "configuration",
    title: "参数与面板配置",
    summary: "配置面板、旋钮、设备业务存储、图片资源和语音命名。",
  },
  {
    id: "scene_automation",
    title: "情景与自动化",
    summary: "维护情景、创建自动化和查询自动化能力。",
  },
  {
    id: "home_organization",
    title: "首页组织与收藏",
    summary: "维护收藏、排序和首页展示结构。",
  },
  {
    id: "maintenance_account",
    title: "维护、诊断与账号",
    summary: "处理升级、统计、诊断、账号和三方登录能力。",
  },
];

const METADATA_GROUP_IDS = METADATA_GROUPS.map((group) => group.id);

const METADATA_TASKS = [
  {
    id: "family_space.manage_house",
    group: "family_space",
    title: "管理家庭",
    summary: "查询、创建、编辑、删除家庭，并读取或写入家庭属性。",
    userPhrases: ["查看我的家庭", "新建一个家庭", "把家庭名称改一下", "读取家庭属性"],
    priority: "P0",
    maxSideEffect: "S2",
    requiredContext: ["userId 或登录态"],
    commonInputs: ["houseId", "name", "description", "properties"],
    actions: ["list", "list_all", "get_detail", "create", "update", "delete", "get_property", "update_property"],
  },
  {
    id: "family_space.manage_room",
    group: "family_space",
    title: "管理房间",
    summary: "查询、新建、批量新建、编辑、删除房间，并支持房间搜索。",
    userPhrases: ["创建一个客厅", "把灯移动到卧室", "删除这个房间", "搜索房间"],
    priority: "P0",
    maxSideEffect: "S2",
    requiredContext: ["houseId"],
    commonInputs: ["roomId", "name", "areaIds", "pageNo", "pageSize", "fuzzyName"],
    actions: ["list", "list_all", "get_detail", "create", "batch_create", "update", "delete", "search_room", "update_room_area"],
  },
  {
    id: "family_space.manage_area",
    group: "family_space",
    title: "管理区域",
    summary: "管理家庭内区域和旧版区域分组，支持区域创建、编辑、删除和模糊搜索。",
    userPhrases: ["创建一个一楼区域", "把房间加入区域", "搜索区域", "删除区域分组"],
    priority: "P1",
    maxSideEffect: "S2",
    requiredContext: ["houseId"],
    commonInputs: ["areaId", "groupId", "name", "roomIds", "fuzzyName"],
    actions: ["list_area", "get_detail_area", "create_area", "update_area", "delete_area", "list_area_group", "list_all_area_group", "fuzzy_search_area_group", "create_area_group", "update_area_group", "delete_area_group"],
  },
  {
    id: "family_space.manage_member_share",
    group: "family_space",
    title: "管理家庭成员与分享",
    summary: "查询成员、邀请成员、接受分享、移除成员、转移管理员和退出家庭。",
    userPhrases: ["邀请家人加入家庭", "查看家庭成员", "移除成员", "转移家庭管理员"],
    priority: "P1",
    maxSideEffect: "S2",
    requiredContext: ["houseId"],
    commonInputs: ["memberId", "role", "shareId", "barcode", "targetUser"],
    actions: ["get_current_member", "list", "search", "remove", "update_member_role", "create_share_barcode", "list_share_history", "send_share_invite", "accept_share_invite", "accept_share_barcode", "quit_house", "transfer_house"],
  },
  {
    id: "device_onboarding.create_device_slot",
    group: "device_onboarding",
    title: "创建设备槽位",
    summary: "为新设备创建云端槽位，是大多数配网流程的前置动作。",
    userPhrases: ["添加一个新设备", "添加设备", "创建设备", "新增设备", "创建灯", "添加灯", "新增灯具", "创建虚拟设备", "create device", "add device", "给这个灯创建槽位", "批量添加这些蓝牙 Mesh 设备"],
    priority: "P0",
    maxSideEffect: "S2",
    requiredContext: ["houseId", "roomId"],
    commonInputs: ["name", "pid", "gatewayDeviceId", "mac", "connectType", "isVirtual", "devices"],
    actions: ["create", "batch_create", "list_all_device", "list_device_snapshot"],
  },
  {
    id: "device_onboarding.pair_device",
    group: "device_onboarding",
    title: "设备配网",
    summary: "覆盖预绑定屏、Matter 配对码、BLE 或移动端辅助配网流程。",
    userPhrases: ["给设备配网", "申请 Matter 配对码", "取消配对", "查询配对进度"],
    priority: "P1",
    maxSideEffect: "S2",
    requiredContext: ["houseId", "deviceId"],
    commonInputs: ["deviceId", "gatewayDeviceId", "pairingCode", "timeout"],
    actions: ["pre_bind_screen", "apply_pairing_code", "apply_secondary_pairing", "cancel_secondary_pairing", "get_secondary_pairing_progress", "requires_ble", "manual_assist"],
  },
  {
    id: "device_onboarding.manage_gateway_onboarding",
    group: "device_onboarding",
    title: "网关接入",
    summary: "查询、绑定、解绑网关，并同步局域网关节点。",
    userPhrases: ["添加网关", "查看网关", "解绑网关", "同步网关节点"],
    priority: "P1",
    maxSideEffect: "S2",
    requiredContext: ["houseId", "gatewayId"],
    commonInputs: ["gatewayId", "mac", "pid", "name"],
    actions: ["list_gateway_with_stats", "get_gateway_detail", "bind_gateway", "unbind_gateway", "delete_gateway", "get_gateway_thread_info", "sync_lan_gateway_nodes", "manual_assist"],
  },
  {
    id: "device_management.query_device",
    group: "device_management",
    title: "查询设备",
    summary: "按家庭、房间、资源或 PID 查询设备详情和设备列表。",
    userPhrases: ["查看设备", "查询灯", "查看某个房间设备", "查询设备详情"],
    priority: "P0",
    maxSideEffect: "S0",
    requiredContext: ["houseId"],
    commonInputs: ["deviceId", "roomId", "pid", "pageNo", "pageSize"],
    actions: ["list_all_device", "get_device_detail", "get_by_pid", "list_relation_device", "list_control_node", "list_ptx_device", "list_device_snapshot"],
  },
  {
    id: "device_management.update_device",
    group: "device_management",
    title: "修改设备信息",
    summary: "修改设备名称、房间、属性和语音可控节点。",
    userPhrases: ["修改设备名称", "移动设备到房间", "更新设备属性"],
    priority: "P1",
    maxSideEffect: "S2",
    requiredContext: ["houseId", "deviceId"],
    commonInputs: ["deviceId", "name", "roomId", "attributes", "nodeId"],
    actions: ["batch_update_name", "update_device_attribute", "update_control_node", "update_room_area", "manual_assist"],
  },
  {
    id: "device_management.remove_device",
    group: "device_management",
    title: "解绑或删除设备",
    summary: "解绑、删除设备，或解绑并清除 MAC。",
    userPhrases: ["删除设备", "解绑设备", "清除设备 MAC"],
    priority: "P1",
    maxSideEffect: "S3",
    requiredContext: ["houseId", "deviceId"],
    commonInputs: ["deviceId", "clearMac", "reason"],
    actions: ["delete_device", "unbind", "unbind_and_clear_mac", "remove", "manual_assist"],
  },
  {
    id: "device_management.manage_device_group",
    group: "device_management",
    title: "设备打组",
    summary: "创建、更新、删除设备组，查询设备组详情并维护成员。",
    userPhrases: ["创建设备组", "查看灯组", "更新设备组成员"],
    priority: "P1",
    maxSideEffect: "S2",
    requiredContext: ["houseId", "groupId"],
    commonInputs: ["groupId", "name", "deviceIds", "addDeviceList", "removeDeviceList"],
    actions: ["create", "get_group_detail", "update", "delete", "update_group_devices", "list_group_snapshot"],
  },
  {
    id: "configuration.configure_panel",
    group: "configuration",
    title: "配置面板按键",
    summary: "配置面板布局、按键动作、重置事件和批量更新事件。",
    userPhrases: ["配置面板", "设置按键动作", "更新面板布局"],
    priority: "P1",
    maxSideEffect: "S2",
    requiredContext: ["deviceId"],
    commonInputs: ["deviceId", "layout", "events", "buttonId"],
    actions: ["get_single_detail", "update_layout", "update_event", "batch_update_event", "reset_event", "get_multi_detail"],
  },
  {
    id: "configuration.configure_knob",
    group: "configuration",
    title: "配置旋钮",
    summary: "查询、更新和重置单键或多键旋钮配置。",
    userPhrases: ["配置旋钮", "重置旋钮", "更新多键旋钮"],
    priority: "P1",
    maxSideEffect: "S2",
    requiredContext: ["deviceId"],
    commonInputs: ["deviceId", "config", "events"],
    actions: ["get_single_detail", "update_single", "reset_single", "get_multi_detail", "update_multi", "reset_multi"],
  },
  {
    id: "configuration.configure_storage_asset",
    group: "configuration",
    title: "配置存储与资源",
    summary: "读取或写入设备业务存储，上传或删除图片资源。",
    userPhrases: ["设置设备存储", "上传图片", "删除图片"],
    priority: "P2",
    maxSideEffect: "S2",
    requiredContext: ["deviceId"],
    commonInputs: ["deviceId", "key", "value", "imageIds"],
    actions: ["get_storage", "set_storage", "upload_image", "delete_images", "text_to_image"],
  },
  {
    id: "configuration.configure_ai_voice",
    group: "configuration",
    title: "配置语音与 AI 名称",
    summary: "查询语音产品、推荐设备或情景名称，并配置语音可控节点。",
    userPhrases: ["推荐设备名称", "推荐情景名称", "查询语音产品"],
    priority: "P2",
    maxSideEffect: "S2",
    requiredContext: ["houseId"],
    commonInputs: ["deviceId", "sceneId", "nodeId", "name"],
    actions: ["list_voice_product", "recommend_device_name", "recommend_scene_name", "list_control_node", "update_control_node", "check_yeelight_connectivity", "get_asr_temp_credential"],
  },
  {
    id: "scene_automation.manage_scene",
    group: "scene_automation",
    title: "管理情景",
    summary: "查询、新建、编辑、删除情景，并维护房间情景排序。",
    userPhrases: ["创建情景", "查看情景", "删除情景", "搜索情景"],
    priority: "P1",
    maxSideEffect: "S2",
    requiredContext: ["houseId", "sceneId"],
    commonInputs: ["sceneId", "name", "actions", "roomId"],
    actions: ["list_all_scene", "get_scene_detail", "search_scene", "create", "update", "delete", "list_room_scene_sort", "update_sort", "list_scene_snapshot"],
  },
  {
    id: "scene_automation.manage_automation",
    group: "scene_automation",
    title: "管理自动化",
    summary: "分页查询、创建、更新、启停、测试和删除自动化规则。",
    userPhrases: ["创建自动化", "关闭自动化", "测试自动化", "删除自动化"],
    priority: "P1",
    maxSideEffect: "S2",
    requiredContext: ["houseId", "automationId"],
    commonInputs: ["automationId", "name", "conditions", "actions", "enabled"],
    actions: ["page_rule", "get_detail", "create", "update", "delete", "enable_rule", "disable_rule", "test_rule", "list_capability", "list_capability_v2", "list_automation_snapshot", "get_progress", "cancel"],
  },
  {
    id: "scene_automation.query_automation_capability",
    group: "scene_automation",
    title: "查询自动化能力",
    summary: "查询自动化能力、规则能力 schema 和可用设备情景能力。",
    userPhrases: ["查询自动化能力", "自动化支持什么条件", "自动化支持什么动作"],
    priority: "P2",
    maxSideEffect: "S0",
    requiredContext: ["houseId"],
    commonInputs: ["houseId", "pid", "deviceId"],
    actions: ["list_capability", "list_capability_v2", "recommend_device", "recommend_scene"],
  },
  {
    id: "home_organization.manage_favorite",
    group: "home_organization",
    title: "管理收藏",
    summary: "查询、新增、批量更新和删除首页收藏。",
    userPhrases: ["添加收藏", "删除收藏", "查看收藏"],
    priority: "P2",
    maxSideEffect: "S2",
    requiredContext: ["houseId"],
    commonInputs: ["items", "deviceIds", "sceneIds"],
    actions: ["list_all_favorite", "batch_insert_favorite", "batch_update_favorite", "batch_delete_favorite"],
  },
  {
    id: "home_organization.manage_sort",
    group: "home_organization",
    title: "管理排序",
    summary: "维护首页展示顺序、情景排序和房间排序。",
    userPhrases: ["调整首页排序", "调整房间排序", "更新情景排序"],
    priority: "P2",
    maxSideEffect: "S2",
    requiredContext: ["houseId"],
    commonInputs: ["items", "roomIds", "sceneIds"],
    actions: ["add_sort", "update_sort", "list_room_snapshot", "list_scene_snapshot"],
  },
  {
    id: "maintenance_account.upgrade_and_stats",
    group: "maintenance_account",
    title: "升级与统计",
    summary: "查询 APP、OTA、用电统计和升级文件。",
    userPhrases: ["查询用电统计", "查看 OTA", "获取最新 APP"],
    priority: "P2",
    maxSideEffect: "S0",
    requiredContext: ["houseId"],
    commonInputs: ["deviceId", "pid", "version"],
    actions: ["get_electricity_stat", "list_ptx_ota_update", "download_ptx_ota_file", "get_latest_app"],
  },
  {
    id: "maintenance_account.manage_account",
    group: "maintenance_account",
    title: "账号与登录",
    summary: "处理账号信息、扫码登录、三方绑定和账号解绑。",
    userPhrases: ["查看账号", "扫码登录", "绑定三方账号", "解绑三方账号"],
    priority: "P2",
    maxSideEffect: "S3",
    requiredContext: ["userId 或登录态"],
    commonInputs: ["account", "qrcode", "state", "provider"],
    actions: ["get_user_info", "update_user_info", "check_account_exists", "create_scan_qrcode", "mark_qrcode_scanned", "check_scan_qrcode", "confirm_scan_login", "scan_login", "generate_third_party_state", "third_party_login", "bind_third_party", "unbind_third_party", "list_third_party_binding"],
  },
  {
    id: "maintenance_account.diagnostics",
    group: "maintenance_account",
    title: "诊断与外部能力",
    summary: "执行诊断、检查连通性、发现 Sonos 分组和下载辅助信息。",
    userPhrases: ["诊断设备", "检查连通性", "发现 Sonos"],
    priority: "P3",
    maxSideEffect: "S1",
    requiredContext: ["houseId"],
    commonInputs: ["deviceId", "groupId", "timeout"],
    actions: ["check_yeelight_connectivity", "diagnose", "download", "discover_sonos_group", "manual_assist"],
  },
];

const TASK_ACTION_SCHEMA = {
  type: "object",
  required: ["task", "action"],
  properties: {
    task: {
      type: "string",
      description: "任务 ID，例如 family_space.manage_room",
    },
    action: {
      type: "string",
      description: "动作 ID，例如 create、list、delete 或 get_house_detail",
    },
    context: {
      type: "object",
      additionalProperties: true,
      description: "执行上下文，例如 houseId、roomId、deviceId、nodeId、runtimeEnv",
      properties: {
        houseId: {
          type: ["string", "null"],
          description: "家庭 ID；CLI 会通过 Header 自动传入，通常可省略",
          default: null,
        },
        roomId: {
          type: ["string", "null"],
          description: "房间 ID",
          default: null,
        },
        deviceId: {
          type: ["string", "null"],
          description: "设备 ID",
          default: null,
        },
        nodeId: {
          type: ["string", "null"],
          description: "节点 ID",
          default: null,
        },
        runtimeEnv: {
          type: ["string", "null"],
          description: "调用方运行环境，例如 local、test、prod",
          default: null,
        },
      },
    },
    payload: {
      type: "object",
      additionalProperties: true,
      description: "动作入参，具体字段请先用 get_action_schema 查询",
    },
    options: {
      type: "object",
      additionalProperties: true,
      description: "执行选项；真实写操作必须显式确认副作用",
      properties: {
        dryRun: {
          type: "boolean",
          description: "是否只返回执行计划，不调用底层接口",
          default: true,
        },
        confirmSideEffect: {
          type: "boolean",
          description: "是否确认 S2/S3 副作用",
          default: false,
        },
        allowCandidate: {
          type: "boolean",
          description: "是否允许执行 candidate action",
          default: false,
        },
        reason: {
          type: ["string", "null"],
          description: "执行原因，建议 S2/S3 操作填写",
          default: null,
        },
      },
    },
  },
};

function getMetadataGroups() {
  return METADATA_GROUPS.map((group) => ({ ...group }));
}

function getMetadataTasks() {
  return METADATA_TASKS.map((task) => ({
    ...task,
    userPhrases: [...task.userPhrases],
    requiredContext: [...task.requiredContext],
    commonInputs: [...task.commonInputs],
    actions: [...task.actions],
  }));
}

module.exports = {
  METADATA_GROUPS,
  METADATA_GROUP_IDS,
  METADATA_SAFETY,
  METADATA_TASKS,
  METADATA_TOOLS,
  TASK_ACTION_SCHEMA,
  getMetadataGroups,
  getMetadataTasks,
};
